name: toybox CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-10.15

    steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
    - uses: mattnite/setup-gyro@v1
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - run: gyro build

  linux-gnu:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
    - uses: mattnite/setup-gyro@v1.0.0
    - uses: actions/checkout@v2
    - run: gyro build

  linux-musl:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
    - uses: mattnite/setup-gyro@v1.0.0
    - uses: actions/checkout@v2
    - run: gyro build -Dtarget=x86_64-linux-musl
